In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os

train_dataset_path = os.listdir('data\data_label_190\data_render2_190_with1_set1_down_center_rot2_s1')

train_subject_types = os.listdir('data\data_label_190\data_render2_190_with1_set1_down_center_rot2_s1')
print(train_subject_types)

['subject1', 'subject10', 'subject100', 'subject101', 'subject102', 'subject103', 'subject104', 'subject105', 'subject106', 'subject107', 'subject108', 'subject109', 'subject11', 'subject110', 'subject111', 'subject112', 'subject113', 'subject114', 'subject115', 'subject116', 'subject117', 'subject118', 'subject119', 'subject12', 'subject120', 'subject121', 'subject122', 'subject123', 'subject124', 'subject125', 'subject126', 'subject127', 'subject128', 'subject129', 'subject13', 'subject130', 'subject131', 'subject132', 'subject133', 'subject134', 'subject135', 'subject136', 'subject137', 'subject138', 'subject139', 'subject14', 'subject140', 'subject141', 'subject142', 'subject143', 'subject144', 'subject145', 'subject146', 'subject147', 'subject148', 'subject149', 'subject15', 'subject150', 'subject151', 'subject152', 'subject153', 'subject154', 'subject155', 'subject156', 'subject157', 'subject158', 'subject159', 'subject16', 'subject160', 'subject161', 'subject162', 'subject163', 

In [10]:
train_subjects = []
test_subjects_labels=[]
input_images=[]
input_labels=[]

for item in train_subject_types:
    all_train_subjects = os.listdir('data\data_label_190\data_render2_190_with1_set1_down_center_rot2_s1' + '/' +item)
    #print(all_subjects)

    path=str('data\data_label_190\data_render2_190_with1_set1_down_center_rot2_s1'  + '/' +item +  '/session1')
    img,label=scan_folder(path,item)
    input_images.append(img)
    input_labels.append(label)
    #print(input_labels)

input_train_images=np.concatenate(input_images,axis=0)  
input_train_labels=np.concatenate(input_labels,axis=0)
print(len(input_train_images))    
print(len(input_train_labels))
print(input_train_images)

3990
3990
[[[[57 57 57]
   [57 57 57]
   [54 54 54]
   ...
   [69 69 69]
   [68 68 68]
   [68 68 68]]

  [[57 57 57]
   [57 57 57]
   [54 54 54]
   ...
   [69 69 69]
   [68 68 68]
   [68 68 68]]

  [[57 57 57]
   [56 56 56]
   [54 54 54]
   ...
   [69 69 69]
   [68 68 68]
   [68 68 68]]

  ...

  [[41 41 41]
   [41 41 41]
   [41 41 41]
   ...
   [74 74 74]
   [74 74 74]
   [74 74 74]]

  [[41 41 41]
   [41 41 41]
   [41 41 41]
   ...
   [73 73 73]
   [74 74 74]
   [74 74 74]]

  [[41 41 41]
   [41 41 41]
   [41 41 41]
   ...
   [73 73 73]
   [74 74 74]
   [74 74 74]]]


 [[[67 67 67]
   [67 67 67]
   [70 70 70]
   ...
   [47 47 47]
   [45 45 45]
   [45 45 45]]

  [[67 67 67]
   [67 67 67]
   [70 70 70]
   ...
   [47 47 47]
   [45 45 45]
   [45 45 45]]

  [[67 67 67]
   [67 67 67]
   [70 70 70]
   ...
   [47 47 47]
   [45 45 45]
   [45 45 45]]

  ...

  [[37 37 37]
   [37 37 37]
   [38 38 38]
   ...
   [97 97 97]
   [98 98 98]
   [98 98 98]]

  [[37 37 37]
   [37 37 37]
   [38 38 38]
  

In [11]:
import os
import cv2
from PIL import Image
from io import BytesIO



def scan_folder(train_dataset_path,label):
    images = []
    labels=[]
    complete_path=[x[0] for x in os.walk(train_dataset_path)]
    for file_name in complete_path:
        #print(file_name)
        for fn in  os.listdir(file_name) :
            # print(fn)
            if fn.endswith(".bmp"):
            # if it's a txt file, print its name (or do whatever you want)
                # print(file_name)
                #im = Image.open(file_name+'/'+fn)
                im = cv2.imread(file_name+'/'+fn)
                # im.show()
                img_arr=cv2.resize(im,(224,224))
                images.append(img_arr)
                labels.append(label)
                #print(im.size)
                #print(im.filename)
             
        
        else:
            current_path = "".join((train_dataset_path, "/", file_name))
            if os.path.isdir(current_path):
                # if we're checking a sub-directory, recursively call this method
                scan_folder(current_path)
    #print(images)
    return images,labels

total_train_images = []
for i in train_subjects: 
    total_train_images += scan_folder(i)

In [12]:
test_dataset_path = os.listdir('data\data_label_190\data_render2_190_with1_down_s2_ori')

test_subject_types = os.listdir('data\data_label_190\data_render2_190_with1_down_s2_ori')
print(test_subject_types)

['subject1', 'subject10', 'subject100', 'subject101', 'subject102', 'subject103', 'subject104', 'subject105', 'subject106', 'subject107', 'subject108', 'subject109', 'subject11', 'subject110', 'subject111', 'subject112', 'subject113', 'subject114', 'subject115', 'subject116', 'subject117', 'subject118', 'subject119', 'subject12', 'subject120', 'subject121', 'subject122', 'subject123', 'subject124', 'subject125', 'subject126', 'subject127', 'subject128', 'subject129', 'subject13', 'subject130', 'subject131', 'subject132', 'subject133', 'subject134', 'subject135', 'subject136', 'subject137', 'subject138', 'subject139', 'subject14', 'subject140', 'subject141', 'subject142', 'subject143', 'subject144', 'subject145', 'subject146', 'subject147', 'subject148', 'subject149', 'subject15', 'subject150', 'subject151', 'subject152', 'subject153', 'subject154', 'subject155', 'subject156', 'subject157', 'subject158', 'subject159', 'subject16', 'subject160', 'subject161', 'subject162', 'subject163', 

In [13]:
test_subjects = []
test_subjects_labels=[]
input_images=[]
input_labels=[]
for item in test_subject_types:
    all_test_subjects = os.listdir('data\data_label_190\data_render2_190_with1_down_s2_ori' + '/' +item)
    #print(item)
    path=str('data\data_label_190\data_render2_190_with1_down_s2_ori' + '/' +item +  '/session2')
    img,label=scan_folder(path,item)
    input_images.append(img)
    input_labels.append(label)

input_test_images=np.concatenate(input_images,axis=0)  
input_test_labels=np.concatenate(input_labels,axis=0)
print(len(input_test_images))    
print(len(input_test_labels))
print(input_test_images[5])
print(input_test_labels[0])

1140
1140
[[[21 21 21]
  [21 21 21]
  [22 22 22]
  ...
  [21 21 21]
  [21 21 21]
  [21 21 21]]

 [[21 21 21]
  [21 21 21]
  [22 22 22]
  ...
  [21 21 21]
  [21 21 21]
  [21 21 21]]

 [[16 16 16]
  [16 16 16]
  [17 17 17]
  ...
  [17 17 17]
  [17 17 17]
  [16 16 16]]

 ...

 [[25 25 25]
  [25 25 25]
  [26 26 26]
  ...
  [25 25 25]
  [25 25 25]
  [25 25 25]]

 [[34 34 34]
  [34 34 34]
  [35 35 35]
  ...
  [34 34 34]
  [34 34 34]
  [34 34 34]]

 [[34 34 34]
  [34 34 34]
  [35 35 35]
  ...
  [34 34 34]
  [34 34 34]
  [34 34 34]]]
subject1


In [14]:
import os
import cv2
from PIL import Image
from io import BytesIO



def scan_folder(test_dataset_path,label):
    images = []
    labels=[]
    #print(test_dataset_path)
    complete_path=[x[0] for x in os.walk(test_dataset_path)]
    #print(complete_path)
    for file_name in complete_path:
        #print(file_name)
        for fn in  os.listdir(file_name) :
            # print(fn)
            if fn.endswith(".bmp"):
            # if it's a txt file, print its name (or do whatever you want)
                # print(file_name)
                #im = Image.open(file_name+'/'+fn)
                im = cv2.imread(file_name+'/'+fn)
                # im.show()
                img_arr=cv2.resize(im,(224,224))
                images.append(img_arr)
                labels.append(label)
             
        
        else:
            current_path = "".join((test_dataset_path, "/", file_name))
            if os.path.isdir(current_path):
                # if we're checking a sub-directory, recursively call this method
                scan_folder(current_path)
    #print(images)
    return images,labels

total_test_images = []
for i in test_subjects: 
    #print(test_subjects)
    total_test_images += scan_folder(i)

In [15]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Dense, Flatten

In [16]:
X_train = input_train_images
Y_train = input_train_labels

X_test = input_test_images
Y_test = input_test_labels

In [17]:
print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

(3990, 224, 224, 3)
(3990,)
(1140, 224, 224, 3)
(1140,)


In [18]:
X_train = X_train/22.0
X_test = X_test/35.0

In [19]:
X_train[1,:]
X_test[1,:]

array([[[0.6       , 0.6       , 0.6       ],
        [0.6       , 0.6       , 0.6       ],
        [0.62857143, 0.62857143, 0.62857143],
        ...,
        [0.6       , 0.6       , 0.6       ],
        [0.6       , 0.6       , 0.6       ],
        [0.6       , 0.6       , 0.6       ]],

       [[0.6       , 0.6       , 0.6       ],
        [0.6       , 0.6       , 0.6       ],
        [0.62857143, 0.62857143, 0.62857143],
        ...,
        [0.6       , 0.6       , 0.6       ],
        [0.6       , 0.6       , 0.6       ],
        [0.6       , 0.6       , 0.6       ]],

       [[0.45714286, 0.45714286, 0.45714286],
        [0.45714286, 0.45714286, 0.45714286],
        [0.48571429, 0.48571429, 0.48571429],
        ...,
        [0.48571429, 0.48571429, 0.48571429],
        [0.45714286, 0.45714286, 0.45714286],
        [0.45714286, 0.45714286, 0.45714286]],

       ...,

       [[0.71428571, 0.71428571, 0.71428571],
        [0.71428571, 0.71428571, 0.71428571],
        [0.74285714, 0

In [38]:
from sklearn.preprocessing import LabelEncoder
lb= LabelEncoder()
Y_train = lb.fit_transform(Y_train)
Y_test = lb.fit_transform(Y_test)

In [39]:
import matplotlib.pyplot as plt
import random

In [45]:
model = Sequential([
    Conv2D(256, (3,3), activation = 'relu', input_shape = (224, 224, 3)),
    MaxPooling2D((2,2)),
    
    Conv2D(128, (3,3), activation = 'relu'),
    MaxPooling2D((2,2)),
    
    Conv2D(64, (3,3), activation = 'relu'),
    MaxPooling2D((2,2)),
    
    Conv2D(64, (3,3), activation = 'relu'),
    MaxPooling2D((2,2)),
    
    Flatten(),
    #Dense(64, activation = 'relu'),
    Dense(190, activation = 'softmax')
])

In [40]:
Y_train

array([  0,   0,   0, ..., 189, 189, 189], dtype=int64)

In [46]:
model.compile(loss = 'sparse_categorical_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

In [47]:
model.fit(X_train, Y_train, epochs = 10, batch_size = 64,validation_split=0.2)

Epoch 1/10
50/50 [==============================] - 443s 9s/step - loss: 4.8016 - accuracy: 0.0846 - val_loss: 33.7470 - val_accuracy: 0.0000e+00
Epoch 2/10
50/50 [==============================] - 422s 8s/step - loss: 0.2630 - accuracy: 0.9420 - val_loss: 70.3828 - val_accuracy: 0.0000e+00
Epoch 3/10
50/50 [==============================] - 409s 8s/step - loss: 0.0061 - accuracy: 0.9987 - val_loss: 100.1482 - val_accuracy: 0.0000e+00
Epoch 4/10
50/50 [==============================] - 407s 8s/step - loss: 0.0031 - accuracy: 0.9991 - val_loss: 95.9234 - val_accuracy: 0.0000e+00
Epoch 5/10
50/50 [==============================] - 412s 8s/step - loss: 0.0045 - accuracy: 0.9991 - val_loss: 105.4925 - val_accuracy: 0.0000e+00
Epoch 6/10
50/50 [==============================] - 407s 8s/step - loss: 0.0034 - accuracy: 0.9991 - val_loss: 82.8485 - val_accuracy: 0.0000e+00
Epoch 7/10
50/50 [==============================] - 407s 8s/step - loss: 2.4493e-04 - accuracy: 1.0000 - val_loss: 85.9611

In [49]:
model.evaluate(X_test, Y_test)

36/36 [==============================] - 34s 950ms/step - loss: 18.3054 - accuracy: 0.0509


[18.305418014526367, 0.05087719112634659]

In [68]:
img_height,img_width = 224,224 
#If imagenet weights are being loaded, 
#input must have a static square shape (one of (128, 128), (160, 160), (192, 192), or (224, 224))
base_model = tensorflow.keras.applications.resnet50.ResNet50(weights= None, include_top=False, input_shape= (img_height,img_width,3))

In [69]:
x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dropout(0.7)(x)
predictions = Dense(190, activation= 'softmax')(x)
model = Model(inputs = base_model.input, outputs = predictions)

In [72]:
model.compile(loss = 'sparse_categorical_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

In [76]:
model.fit(X_train, Y_train, epochs = 10, batch_size = 64)

Epoch 1/10
63/63 [==============================] - 597s 9s/step - loss: 3.7093 - accuracy: 0.1368
Epoch 2/10
63/63 [==============================] - 581s 9s/step - loss: 2.4810 - accuracy: 0.3419
Epoch 3/10
63/63 [==============================] - 580s 9s/step - loss: 1.3032 - accuracy: 0.6236
Epoch 4/10
63/63 [==============================] - 580s 9s/step - loss: 0.5504 - accuracy: 0.8361
Epoch 5/10
63/63 [==============================] - 579s 9s/step - loss: 0.2995 - accuracy: 0.9005
Epoch 6/10
63/63 [==============================] - 577s 9s/step - loss: 0.1879 - accuracy: 0.9421
Epoch 7/10
63/63 [==============================] - 577s 9s/step - loss: 0.1645 - accuracy: 0.9456
Epoch 8/10
63/63 [==============================] - 577s 9s/step - loss: 0.0846 - accuracy: 0.9739
Epoch 9/10
63/63 [==============================] - 577s 9s/step - loss: 0.1106 - accuracy: 0.9634
Epoch 10/10
63/63 [==============================] - 575s 9s/step - loss: 0.0982 - accuracy: 0.9659


In [75]:
model.evaluate(X_test, Y_test)

36/36 [==============================] - 40s 1s/step - loss: 10.9570 - accuracy: 0.0044


[10.95698070526123, 0.004385964944958687]

In [23]:
from keras.layers import MaxPool2D

In [24]:
model = Sequential()
model.add(Conv2D(input_shape=(224,224,3),filters=64,kernel_size=(3,3),padding="same", activation="relu"))
model.add(Conv2D(filters=64,kernel_size=(3,3),padding="same", activation="relu"))
model.add(MaxPool2D(pool_size=(2,2),strides=(2,2)))
model.add(Conv2D(filters=128, kernel_size=(3,3), padding="same", activation="relu"))
model.add(Conv2D(filters=128, kernel_size=(3,3), padding="same", activation="relu"))
model.add(MaxPool2D(pool_size=(2,2),strides=(2,2)))
model.add(Conv2D(filters=256, kernel_size=(3,3), padding="same", activation="relu"))
model.add(Conv2D(filters=256, kernel_size=(3,3), padding="same", activation="relu"))
model.add(Conv2D(filters=256, kernel_size=(3,3), padding="same", activation="relu"))
model.add(MaxPool2D(pool_size=(2,2),strides=(2,2)))
model.add(Conv2D(filters=512, kernel_size=(3,3), padding="same", activation="relu"))
model.add(Conv2D(filters=512, kernel_size=(3,3), padding="same", activation="relu"))
model.add(Conv2D(filters=512, kernel_size=(3,3), padding="same", activation="relu"))
model.add(MaxPool2D(pool_size=(2,2),strides=(2,2)))
model.add(Conv2D(filters=512, kernel_size=(3,3), padding="same", activation="relu"))
model.add(Conv2D(filters=512, kernel_size=(3,3), padding="same", activation="relu"))
model.add(Conv2D(filters=512, kernel_size=(3,3), padding="same", activation="relu"))
model.add(MaxPool2D(pool_size=(2,2),strides=(2,2)))

In [56]:
model.add(Flatten())
model.add(Dense(190, activation = 'softmax'))

In [57]:
model.compile(loss = 'sparse_categorical_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

In [58]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_2 (Conv2D)           (None, 224, 224, 64)      1792      
                                                                 
 conv2d_3 (Conv2D)           (None, 224, 224, 64)      36928     
                                                                 
 max_pooling2d (MaxPooling2D  (None, 112, 112, 64)     0         
 )                                                               
                                                                 
 conv2d_4 (Conv2D)           (None, 112, 112, 128)     73856     
                                                                 
 conv2d_5 (Conv2D)           (None, 112, 112, 128)     147584    
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 56, 56, 128)      0         
 2D)                                                  

In [59]:
model.fit(X_train, Y_train, epochs = 10, batch_size = 64)

Epoch 1/10
63/63 [==============================] - 1141s 18s/step - loss: 5.2492 - accuracy: 0.0045
Epoch 2/10
63/63 [==============================] - 1131s 18s/step - loss: 5.2486 - accuracy: 0.0030
Epoch 3/10
63/63 [==============================] - 1130s 18s/step - loss: 5.2486 - accuracy: 0.0045
Epoch 4/10
63/63 [==============================] - 1079s 17s/step - loss: 5.2486 - accuracy: 0.0035
Epoch 5/10
63/63 [==============================] - 1046s 17s/step - loss: 5.2486 - accuracy: 0.0053
Epoch 6/10
63/63 [==============================] - 1046s 17s/step - loss: 5.2485 - accuracy: 0.0053
Epoch 7/10
63/63 [==============================] - 1046s 17s/step - loss: 5.2486 - accuracy: 0.0035
Epoch 8/10
63/63 [==============================] - 1046s 17s/step - loss: 5.2484 - accuracy: 0.0033
Epoch 9/10
63/63 [==============================] - 1046s 17s/step - loss: 5.2485 - accuracy: 0.0035
Epoch 10/10
63/63 [==============================] - 1047s 17s/step - loss: 5.2484 - accura